steer_drive_controller:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    left_steering_hinge_controller:
        type: effort_controllers/JointPositionController
        joint: left_steering_hinge_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}

    right_steering_hinge_controller:
        type: effort_controllers/JointPositionController
        joint: right_steering_hinge_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}

    front_left_drive_controller:
        type: effort_controllers/JointPositionController
        joint: front_left_wheel_joint 
        pid: {p: 100.0, i: 0.01, d: 10.0}

    front_right_drive_controller:
        type: effort_controllers/JointPositionController
        joint: front_right_wheel_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}

    rear_left_drive_controller:
        type: effort_controllers/JointPositionController
        joint: rear_left_wheel_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}

    rear_right_drive_controller:
        type: effort_controllers/JointPositionController
        joint: rear_right_wheel_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}

