steer_drive_controller:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    gazebo_ros_control:
        pid_gains:
            left_steering_hinge_joint: {p: 1.00, i: 0.1, d: 1.0}
            right_steering_hinge_joint: {p: 1.00, i: 0.1, d: 1.0}
            front_left_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
            front_right_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
            rear_left_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}
            rear_right_wheel_joint: {p: 100.0, i: 0.01, d: 10.0}

    steering_position_controller:
        type: position_controllers/JointGroupPositionController
        joints:
            - left_steering_hinge_joint
            - right_steering_hinge_joint

    wheel_drive_controller:
        type: effort_controllers/JointGroupEffortController
        joints:
            - front_left_wheel_joint
            - front_right_wheel_joint
            - rear_left_wheel_joint
            - rear_right_wheel_joint
