# All positions (pos) are with respect to chassis origin

stream_track:
  enabled: true
  markers: "/mursim/track"

ground_truth:
  enabled: true

sensors:
  lidar_pipeline:
    node_name: 
    enabled: true 
    pos:
        x: 0.95
        y: 0.0
        z: 0.15
       
  stereo_pipeline:
    enabled: false
    camera_name: stereo_cam               # Camera name
    image_topic_name: image_raw           # Image topic name

    rate: 30                              # Publishing frequency [Hz]

    camera_size: 0.05                     # Size of camera [m]
    camera_mass: 0.1                      # Mass of camera [kg]
    camera_height: 0.5                    # Height of camera [m]
    camera_baseline: 0.15                 # Baseline of stereo camera [m]

  gps_pipeline:
    enabled: true
    topic_name: /piksi/gps
    vel_topic_name: /piksi/velocity
    pos:
        x: 0.0
        y: 0.1
        z: 0.0

  imu_pipeline:
    enabled: true
    topic_name: /piksi/imu
    pos:
        x: 0.0
        y: 0.0
        z: 0.0
